export const CREDITOR_TYPE_OPTIONS = [
  "SOYA CREDITORS",
  "OTHER GRAIN CREDITORS",
  "MEDICINE CREDITORS",
  "CAPEX CREDITORS",
  "SERVICE CREDITORS",
  "IMPORT CREDITORS",
  "MISCELLANEOUS CREDITORS",
  "Maize Creditors",
  "BAJRA Creditors",
  "Wheat Creditors",
  "Mustard DOC Creditors",
  "D.D.G.S Creditors",
  "DEOILED RICE BRAN Creditors",
  "Birds Creditor",
  "Chicks Creditor",
  "Gen Item",
  "Hatching Egg Outside",
  "Premix",
  "Rice Bran Oil",
  "Rice Bran Polish",
  "Rice Kanni",
  "Lime Stone Power",
  "Gaur Meal",
  "Chicken Waste Meal",
  "P.P Bags",
  "Other",
  "ANIMAL FEED SUPLEMENT",
].map((value) => ({ value, label: value }));

export const MASTER_DROPDOWN_PAGE_SIZE = 30;
